/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2c3d6093-f192-4949-a81e-6411dce5af58",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_0pNWunjkY",
    "aws_user_pools_web_client_id": "4ilt6aptlhcr35vm8p9v5e5gbd",
    "oauth": {}
};


export default awsmobile;
